name: update-msbuild
on:
  workflow_dispatch:
  push:
jobs:
  updatemsbuild:
    runs-on: ubuntu-latest
    steps:
      - name: Clone msbuild
        run: |
          git clone https://github.com/dh-hos-code/msbuild.git ./.clonemsbuild
          curl -o ./.clonemsbuild/otherlibraries-main.zip https://github.com/dh-hos-code/otherlibraries/archive/refs/heads/main.zip
     - name: Display files
        run: |
          list=$(ls -R ./)
          echo $list
