name: update-msbuild
on:
  workflow_dispatch:
  push:
jobs:
  updatemsbuild:
    runs-on: ubuntu-latest
    steps:
      - name: Clone msbuild
        run: |
          git clone https://github.com/dh-hos-code/msbuild.git ./.clonemsbuild
      - name: Clone msbuild
        working-directory: ./.clonemsbuild
        run: |
          curl -o ./otherlibraries-main.zip https://github.com/dh-hos-code/otherlibraries/archive/refs/heads/main.zip
          git config --global user.name "ongtrieuhau-dh"
          git config --global user.email "o.ngtrieuhau861@gmail.com"
          git config --unset-all http.https://github.com/.extraheader
          git add ./otherlibraries-main.zip
          git commit -m "Add otherlibraries-main.zip"
          git -c http.extraHeader="${{ secrets.MSBUILDTOKENEXTRAHEADER }}" push -u https://github.com/dh-hos-code/msbuild.git main
      - name: Display files
        if: ${{ always() }}
        run: |
          echo ($-f "./.clonemsbuild/otherlibraries-main.zip")
