name: update-msbuild
on:
  workflow_dispatch:
  push:
jobs:
  updatemsbuild:
    runs-on: ubuntu-latest
    steps:
      - name: Clone msbuild
        run: |
          git clone https://github.com/dh-hos-code/msbuild.git ./.clonemsbuild
          chmod u=rwx ./.clonemsbuild
      - name: Download otherlibraries-main.zip
        working-directory: ./.clonemsbuild
        run: |
          git config --global user.name "ongtrieuhau-dh"
          git config --global user.email "o.ngtrieuhau861@gmail.com"
          FILE=./otherlibraries-main.zip
          if [[ -f $FILE ]]; then
            echo "$FILE exists! => Need removed!!!"
            rm -f $FILE
            git add .
            git commit -m "Remove old otherlibraries-main.zip"
          fi
          if [[ -f $FILE ]]; then
            echo "Check: $FILE exists!"
          else
            echo "Check: $FILE does not exist!"
          fi
          curl -o $FILE https://github.com/dh-hos-code/otherlibraries/archive/refs/heads/main.zip
      - name: Push code
        working-directory: ./.clonemsbuild
        run: |
          FILE=./otherlibraries-main.zip
          if [[ -f $FILE ]]; then
            echo "Check on curl: $FILE exists!"
          else
            echo "Check on curl: $FILE does not exist!"
          fi
          git add .
          git commit -m "Add otherlibraries-main.zip; commit: ${{ github.sha }}; author: ${{ github.actor }}"
          git -c http.extraHeader="${{ secrets.MSBUILDTOKENEXTRAHEADER }}" push -u https://github.com/dh-hos-code/msbuild.git main
