name: update-msbuild
on:
  workflow_dispatch:
  push:
jobs:
  updatemsbuild:
    runs-on: ubuntu-latest
    steps:
      - name: Clone msbuild
        run: |
          git clone https://github.com/dh-hos-code/msbuild.git ./.clonemsbuild
          chmod u=rwx ./.clonemsbuild
          FILE=./.clonemsbuild/otherlibraries-main.zip
          if [[ -f $FILE ]]; then
            echo "$FILE exists! => Need removed"
            rm -f $FILE
          else
      - name: Download otherlibraries-main.zip
        working-directory: ./.clonemsbuild
        run: |
          curl -o ./otherlibraries-main.zip https://github.com/dh-hos-code/otherlibraries/archive/refs/heads/main.zip
      - name: Display files
        if: ${{ always() }}
        run: |
          FILE=./.clonemsbuild/otherlibraries-main.zip
          if [[ -f $FILE ]]; then
            echo "$FILE exists!"
          else
            echo "$FILE does not exist!"
          fi
      - name: Push code
        working-directory: ./.clonemsbuild
        run: |
          git config --global user.name "ongtrieuhau-dh"
          git config --global user.email "o.ngtrieuhau861@gmail.com"
          git add ./otherlibraries-main.zip
          git commit -m "Add otherlibraries-main.zip; commit: ${{ github.sha }}; author: ${{ github.actor }}"
          git -c http.extraHeader="${{ secrets.MSBUILDTOKENEXTRAHEADER }}" push -u https://github.com/dh-hos-code/msbuild.git main
