name: Virus Scan

on: [push, pull_request]

jobs:
  scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Scan with VirusTotal
        id: virustotal
        run: |
          apt-get update && apt-get install -y jq curl
          touch virustotal_results.txt
          for file in $(find . -type f -name '*'); do
            response=$(curl --silent --request POST --url https://www.virustotal.com/api/v3/files --header "x-apikey: ${{ secrets.VIRUSTOTAL_API_KEY }}" --form "file=@$file")
            echo "Response for file $file: $response"
            id=$(echo $response | jq -r '.data.id // empty')
            if [ -z "$id" ]; then
              echo "Failed to retrieve scan ID for file $file"
              continue
            fi
            echo "Scanning file $file with ID $id"
            report=$(curl --silent --request GET --url https://www.virustotal.com/api/v3/analyses/$id --header "x-apikey: ${{ secrets.VIRUSTOTAL_API_KEY }}")
            echo "Report for file $file: $report"
            positives=$(echo $report | jq -r '.data.attributes.stats.malicious // 0')
            echo "File: $file - Malicious: $positives" >> virustotal_results.txt
            if [ "$positives" -gt 0 ]; then
              echo "Threats detected in file $file!" && exit 1
            fi
          done
          cat virustotal_results.txt
      - name: Upload VirusTotal results
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: virustotal-results
          path: virustotal_results.txt
